name: shapepro
description: ShapePro - App profissional de dieta e treino personalizado
publish_to: 'none'
version: 1.0.2+13

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  google_fonts: ^8.0.2
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  
  # State Management
  provider: ^6.1.2
  
  # Firebase
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  firebase_storage: ^13.2.0
  google_mlkit_pose_detection: ^0.14.1
  google_sign_in: ^7.2.0

  # Networking & Storage
  http: ^1.2.2
  shared_preferences: ^2.3.3
  camera: ^0.12.0+1
  image_picker: ^1.0.7
  
  # Charts
  fl_chart: ^1.2.0
  
  # Utils
  intl: ^0.20.2
  local_auth: ^3.0.1
  flutter_localizations:
    sdk: flutter

  in_app_purchase: ^3.2.0
  url_launcher: ^6.3.0
  flutter_local_notifications: ^21.0.0
  timezone: ^0.11.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.1.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"


flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/icon.png
    - assets/images/
    - assets/exercises/

